spring.application.name=admin-management

# K?t n?i SQL Server (S? d?ng instance SQLEXPRESS chu?n)
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=db_admin;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=123456

# JPA / Hibernate (T? ??ng t?o b?ng categories và users)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# C?u hình ???ng d?n View JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp